<?php

/*
 * Справочник групп атрибутов и привязок атрибутов к группам.
 *
 * Используется:
 *  - database/seeders/AttributeGroupSeeder.php    — создаёт группы и раскладывает атрибуты
 *  - app/Console/Commands/AttributesAssignGroups.php — ручной запуск (`php artisan attributes:assign-groups`)
 *  - app/Services/Product/AttributeGroupAssigner.php — общая логика применения маппинга
 *
 * Источник правды для групп — этот файл. После изменения маппинга
 * достаточно запустить `php artisan attributes:assign-groups`.
 *
 * Атрибуты определяются по slug (не по name — имя может поменяться,
 * slug генерится транслитерацией из имени и стабилен).
 *
 * Атрибуты, отсутствующие в `assignments`, остаются со своей текущей группой
 * (в том числе без группы, если она не задана).
 */

return [
    'groups' => [
        ['name' => 'Общие характеристики',        'sort_order' => 10],
        ['name' => 'Внешний вид',                 'sort_order' => 20],
        ['name' => 'Материалы и состав',          'sort_order' => 30],
        ['name' => 'Размеры изделия',             'sort_order' => 40],
        ['name' => 'Параметры одежды',            'sort_order' => 50],
        ['name' => 'Параметры модели на фото',    'sort_order' => 60],
        ['name' => 'Функционал и особенности',    'sort_order' => 70],
        ['name' => 'Питание и управление',        'sort_order' => 80],
        ['name' => 'Применение и уход',           'sort_order' => 90],
        ['name' => 'Упаковка и маркировка',       'sort_order' => 100],
        ['name' => 'Производство и сертификация', 'sort_order' => 110],
    ],

    'assignments' => [
        // === 1. Общие характеристики ===
        'model' => 'Общие характеристики',
        'kollekciia' => 'Общие характеристики',
        'pol' => 'Общие характеристики',
        'naznacenie' => 'Общие характеристики',
        'forma' => 'Общие характеристики',
        'forma-vypuska' => 'Общие характеристики',
        'effekt' => 'Общие характеристики',
        'osnova' => 'Общие характеристики',
        'aromat' => 'Общие характеристики',
        'semeistvo-aromatov' => 'Общие характеристики',
        'analog-aromata' => 'Общие характеристики',
        'tip-parfiumerii' => 'Общие характеристики',
        'vkus' => 'Общие характеристики',
        'bolsoi-razmer' => 'Общие характеристики',
        'podxodit-dlia-marketpleisov' => 'Общие характеристики',
        'ssylka-na-video' => 'Общие характеристики',

        // === 2. Внешний вид ===
        'osnovnoi-cvet' => 'Внешний вид',
        'dopolnitelnyi-cvet' => 'Внешний вид',
        'prozracnost' => 'Внешний вид',
        'dekor' => 'Внешний вид',
        'poverxnost' => 'Внешний вид',
        'svetiashhiisia' => 'Внешний вид',
        'fantaziinyi' => 'Внешний вид',
        'v-vide-zivotnyx' => 'Внешний вид',
        'cvet-volos' => 'Внешний вид',
        'vnesnost' => 'Внешний вид',
        's-ukraseniiami' => 'Внешний вид',
        's-kruzevnoi-rezinkoi' => 'Внешний вид',
        'slepok-pornozvezdy' => 'Внешний вид',

        // === 3. Материалы и состав ===
        'osnovnoi-material' => 'Материалы и состав',
        'dopolnitelnyi-material' => 'Материалы и состав',
        'sostav' => 'Материалы и состав',
        'sostav-izdeliia' => 'Материалы и состав',
        'tkan' => 'Материалы и состав',
        'vid-tkani' => 'Материалы и состав',
        'dop-vid-tkani' => 'Материалы и состав',
        'tolshhina' => 'Материалы и состав',
        'tolshhina-stenki' => 'Материалы и состав',
        'superskolzkie' => 'Материалы и состав',
        'komponenty' => 'Материалы и состав',
        's-relefnoi-poverxnostiu' => 'Материалы и состав',
        's-dopstimuliacieiusiki-vorsinki-pupyryski' => 'Материалы и состав',

        // === 4. Размеры изделия ===
        'obshhaia-dlina-izdeliia-sm' => 'Размеры изделия',
        'rabocaia-dlina-sm' => 'Размеры изделия',
        'rabocaia-dlina-dopolnitelnoi-casti-sm' => 'Размеры изделия',
        'dlina-sm' => 'Размеры изделия',
        'dlina-nasadki-sm' => 'Размеры изделия',
        'dlina-dopolnitelnogo-stimuliatora-sm' => 'Размеры изделия',
        'dlina-kolby-sm' => 'Размеры изделия',
        'dlina-rucki-sm' => 'Размеры изделия',
        'dlina-scepki-sm' => 'Размеры изделия',
        'dlina-falloimitatora-sm' => 'Размеры изделия',
        'dlina-xvosta-sm' => 'Размеры изделия',
        'sirina-diametr-sm' => 'Размеры изделия',
        'diametr-dopolnitelnogo-stimuliatora-sm' => 'Размеры изделия',
        'diametr-osnovaniia-izdeliia-sm' => 'Размеры изделия',
        'diametr-falloimitatora-sm' => 'Размеры изделия',
        'minimalnyi-diametr-osnovnoi-casti-sm' => 'Размеры изделия',
        'maksimalnyi-diametr-osnovnoi-casti-sm' => 'Размеры изделия',
        'minimalnyi-diametr-dopolnitelnoi-casti-sm' => 'Размеры изделия',
        'maksimalnyi-diametr-dopolnitelnoi-casti-sm' => 'Размеры изделия',
        'minimalnyi-diametr-osnovaniia-sm' => 'Размеры изделия',
        'maksimalnyi-diametr-osnovaniia-sm' => 'Размеры изделия',
        'minimalnyi-diametr-sara-sm' => 'Размеры изделия',
        'maksimalnyi-diametr-sara-sm' => 'Размеры изделия',
        'kolicestvo-sarov' => 'Размеры изделия',
        'rasstoianie-mezdu-sarami-sm' => 'Размеры изделия',
        'vysota-sm' => 'Размеры изделия',
        'amplituda-traektorii-dvizeniia-nasadki-sm' => 'Размеры изделия',
        'kolicestvo-xvostov' => 'Размеры изделия',
        'obieem-ml' => 'Размеры изделия',
        'ves-mg' => 'Размеры изделия',
        'korrekciia-razmerov' => 'Размеры изделия',

        // === 5. Параметры одежды ===
        'razmer' => 'Параметры одежды',
        'rost-sm' => 'Параметры одежды',
        'rostovka-sm' => 'Параметры одежды',
        'anatomiia' => 'Параметры одежды',
        's-zavysennoi-taliei' => 'Параметры одежды',
        's-zanizennoi-taliei' => 'Параметры одежды',
        's-otkrytymi-iagodicami' => 'Параметры одежды',
        's-otkrytoi-grudiu' => 'Параметры одежды',
        's-dostupom' => 'Параметры одежды',
        'so-svom-szadi' => 'Параметры одежды',
        'podtiagivaiushhie' => 'Параметры одежды',
        'vid-trusov' => 'Параметры одежды',

        // === 6. Параметры модели на фото ===
        'obxvat-grudi-modeli-na-foto-sm' => 'Параметры модели на фото',
        'obxvat-talii-modeli-na-foto-sm' => 'Параметры модели на фото',
        'obxvat-beder-modeli-na-foto-sm' => 'Параметры модели на фото',
        'rost-modeli-na-foto-sm' => 'Параметры модели на фото',

        // === 7. Функционал и особенности ===
        's-vibraciei' => 'Функционал и особенности',
        's-vnutrennei-vibraciei' => 'Функционал и особенности',
        's-rotaciei' => 'Функционал и особенности',
        's-nagrevom' => 'Функционал и особенности',
        's-golosom' => 'Функционал и особенности',
        's-dozatorom' => 'Функционал и особенности',
        's-massaznymi-sarikami' => 'Функционал и особенности',
        's-nasadkami' => 'Функционал и особенности',
        's-nasadkoi-v-vide-vaginy' => 'Функционал и особенности',
        's-kolcom' => 'Функционал и особенности',
        's-originalnym-krepleniem' => 'Функционал и особенности',
        's-rukoiatiu-v-forme-fallosa' => 'Функционал и особенности',
        'so-smeshhennym-centrom-tiazesti' => 'Функционал и особенности',
        'na-kreplenii' => 'Функционал и особенности',
        'na-prisoske' => 'Функционал и особенности',
        'na-radioupravlenii' => 'Функционал и особенности',
        'gibkii' => 'Функционал и особенности',
        'gnushhiisia' => 'Функционал и особенности',
        'dvustoronnii' => 'Функционал и особенности',
        'naduvnoi' => 'Функционал и особенности',
        's-mosonkoi' => 'Функционал и особенности',
        'v-kolbe' => 'Функционал и особенности',
        'v-odezde' => 'Функционал и особенности',
        'mernaia-skala' => 'Функционал и особенности',
        'zivye' => 'Функционал и особенности',
        'regulirovka-vysoty' => 'Функционал и особенности',
        'regulirovka-ugla-naklona' => 'Функционал и особенности',
        'adapter-dlia-smeny-nasadki' => 'Функционал и особенности',
        'nasos' => 'Функционал и особенности',
        'instrument-otkacki-vozduxa' => 'Функционал и особенности',
        'sposob-pompirovaniia' => 'Функционал и особенности',
        'kontrol-davleniia' => 'Функционал и особенности',
        'tip-krepleniia' => 'Функционал и особенности',
        'osnovanie' => 'Функционал и особенности',
        'kolicestvo-nasadok-v-komplekte' => 'Функционал и особенности',
        'stimuliaciia-klitora' => 'Функционал и особенности',
        'stimuliaciia-prostaty' => 'Функционал и особенности',
        'stimuliaciia-tocki-g' => 'Функционал и особенности',
        'so-stimuliaciei-anusa' => 'Функционал и особенности',
        's-analnoi-stimuliaciei' => 'Функционал и особенности',
        'dlia-analnogo-fistinga' => 'Функционал и особенности',
        'podviznye-casti-tela' => 'Функционал и особенности',
        'realisticnye-casti-tela' => 'Функционал и особенности',
        'poziciia' => 'Функционал и особенности',
        'pokalyvaiushhie' => 'Функционал и особенности',
        's-anesteziruiushhim-effektom' => 'Функционал и особенности',
        's-omolazivaiushhim-effektom' => 'Функционал и особенности',
        's-protivovospalitelnym-effektom' => 'Функционал и особенности',
        's-uvlazniaiushhim-effektom' => 'Функционал и особенности',
        'c-feromonami' => 'Функционал и особенности',
        'dlia-par' => 'Функционал и особенности',
        'dlia-doma' => 'Функционал и особенности',
        'avtomobilnye' => 'Функционал и особенности',
        'castota-postupatelnoi-traektorii-dvizeniia-nasadki' => 'Функционал и особенности',

        // === 8. Питание и управление ===
        'tip-upravleniia' => 'Питание и управление',
        'interfeis' => 'Питание и управление',
        'upravlenie-s-prilozeniia' => 'Питание и управление',
        'pitanie-osnovnogo-ustroistva' => 'Питание и управление',
        'kolicestvo-i-tip-batareek-dlia-osnovnogo-ustroistva' => 'Питание и управление',
        'tip-batareek' => 'Питание и управление',
        'pitanie-pulta-pri-nalicii-pulta' => 'Питание и управление',
        'kolicestvo-i-tip-batareek-dlia-pulta-pri-nalicii-pulta' => 'Питание и управление',
        'nalicie-pulta-upravleniia' => 'Питание и управление',
        'kolicestvo-motorov' => 'Питание и управление',
        'kolicestvo-rezimov-vibracii' => 'Питание и управление',
        'kolicestvo-rezimov-rotacii' => 'Питание и управление',
        'kolicestvo-rezimov-elektrostimuliacii' => 'Питание и управление',
        'kolicestvo-skorostei' => 'Питание и управление',
        'izmeniaemaia-intensivnost-vibracii' => 'Питание и управление',
        'izmeniaemaia-intensivnost-elektrostimuliacii' => 'Питание и управление',
        'vremia-zariadki-min' => 'Питание и управление',
        'vremia-raboty-ustroistva-v-aktivnom-rezime-pri-polnoi-zariadke-min' => 'Питание и управление',
        'uroven-suma-db' => 'Питание и управление',
        'uroven-vlagozashhity' => 'Питание и управление',
        's-podsvetkoi-indikatora-zariadki' => 'Питание и управление',
        's-podsvetkoi-knopok' => 'Питание и управление',

        // === 9. Применение и уход ===
        'rekomendacii-po-primeneniiu' => 'Применение и уход',
        'sposob-naneseniia' => 'Применение и уход',
        'pokazaniia-k-primeneniiu' => 'Применение и уход',
        'protivopokazaniia' => 'Применение и уход',
        'prodolzitelnost-priema' => 'Применение и уход',
        'usloviia-xraneniia-i-obrabotki' => 'Применение и уход',

        // === 10. Упаковка и маркировка ===
        'kolicestvo-v-komplekte' => 'Упаковка и маркировка',
        'kolicestvo-izdelii-v-roznicnoi-upakovke' => 'Упаковка и маркировка',
        'kolicestvo-izdelii-v-upakovke' => 'Упаковка и маркировка',
        'tip-upakovki' => 'Упаковка и маркировка',
        'material-upakovki' => 'Упаковка и маркировка',
        'rekomendacii-po-upakovke' => 'Упаковка и маркировка',
        'markirovannyi-tovar' => 'Упаковка и маркировка',
        'pecatat-kod-markirovki-v-dvux-ekzempliarax' => 'Упаковка и маркировка',
        'dopolnitelnaia-informaciia-dlia-etiketki' => 'Упаковка и маркировка',

        // === 11. Производство и сертификация ===
        'izgotovitel' => 'Производство и сертификация',
        'adres-proizovoditelia' => 'Производство и сертификация',
        'principal' => 'Производство и сертификация',
        'adres-principala' => 'Производство и сертификация',
        'importer' => 'Производство и сертификация',
        'fabrika' => 'Производство и сертификация',
        'strana-proisxozdeniia' => 'Производство и сертификация',
        'data-proizvodstva' => 'Производство и сертификация',
        'srok-xraneniia-mes' => 'Производство и сертификация',
        'srok-sluzby-mes' => 'Производство и сертификация',
        'srok-godnosti-goden-do' => 'Производство и сертификация',
        'klassifikaciia-dlia-otcetnosti' => 'Производство и сертификация',
        'nomer-tex-reglamenta-standarta-na-produkciiu' => 'Производство и сертификация',
        'pricina-likvidacii' => 'Производство и сертификация',
    ],
];
