[program:pulse]
process_name=%(program_name)s
command=php /var/www/artisan pulse:check
autostart=true
autorestart=true
user=laravel
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/pulse.log
